export const GIG_CATEGORIES = [
  "Home Repair",
  "Plumbing",
  "Electrical",
  "Cleaning",
  "Moving",
  "Yard Work",
  "Painting",
  "Carpentry",
  "Handyman",
  "Tutoring",
  "Pet Care",
  "Babysitting",
  "Delivery",
  "Tech Support",
  "Web Design",
  "Graphic Design",
  "Writing",
  "Photography",
  "Event Help",
  "Auto Services",
  "Misc",
] as const;

